services:
  db:
    image: postgres:17.5-alpine
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=call_of_cthulhu
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d  # pasta local com scripts SQL
volumes:
  pg-data:
