services:
  db:
    image: postgres:17.5-alpine
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=call_of_chtulhu
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: