site_name: Call of Cthulhu
site_description: Documentação de desenvolvimento do Projeto Call of Cthulhu da Disciplina Bancos de Dados da Universidade de Brasília
repo_name: "2025.1-Call_of_Cthulhu"
repo_url: https://github.com/SBD1/2025.1-Call_of_Cthulhu

nav:
  - Início: index.md
  - Entregas:
      - Primeira: entregas/entrega1.md
      - Segunda: entregas/entrega2.md
      - Terceira: entregas/entrega3.md
      - Final: entregas/entrega-final.md
  - Referências: referencias/referencias.md 
  - Backlog: backlog/backlog.md

theme:
  name: material
  language: pt-BR

  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - navigation.footer


  palette:
    - scheme: default
      primary: "deep purple"
      accent: "deep purple"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - scheme: slate
      primary: "deep purple"
      accent: "deep purple"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  logo:
  favicon:
  
# For image rendering
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - glightbox:
       touchNavigation: true
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       caption_position: bottom

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wChrstphr
      name: "Christopher Paraizo"
    - icon: fontawesome/brands/github
      link: https://github.com/JJOAOMARCOSS
      name: "João Marcos"
    - icon: fontawesome/brands/github
      link: https://github.com/Cayoalencar
      name: "Cayo Alencar"
    - icon: fontawesome/brands/github
      link: https://github.com/luizfaria1989
      name: "Luiz Faria"
    - icon: fontawesome/brands/github
      link: https://github.com/igorvdaniel
      name: "Igor Daniel"