site_name: Call of Cthulhu
site_description: Documentação Oficial do Projeto Call of Cthulhu da Disciplina Bancos de Dados da Universidade de Brasília
site_url: https://github.com/SBD1/2025.1-CallOfCthulhu
site_author: Grupo 01 - Engenharia de Requisitos - UnB
repo_name: CallofCthulhu
repo_url: https://github.com/SBD1/2025.1-CallOfCthulhu
edit_uri: edit/docs/docs/

theme:
  name: material
  language: pt-BR
  custom_dir: overrides
  logo: assets/logo.png  # Adiciona o logo
  favicon: assets/favicon.ico  # Adiciona o favicon
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking
# Paleta
  palette:
    # Modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "teal"
      accent: "brown"
      toggle:
        icon: material/weather-night
        name: Mudar para o tema escuro
    # Modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "teal"
      accent: "brown"
      toggle:
        icon: material/weather-sunny
        name: Mudar para o tema claro
  
# For image rendering
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

plugins:
  - glightbox:
       touchNavigation: true
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       caption_position: bottom

nav:
  - Início: index.md
  - Apresentação: entregas/apresentacao/apresentacao.md
  - Entregas 1:
      - DER: entregas/primeira/DER.md
      - MER: entregas/primeira/MER.md
      - ML: entregas/primeira/ML.md
      - DD: entregas/primeira/DD.md
  - Entregas 2:
      - DER: entregas/segunda/DER.md
      - MER: entregas/segunda/MER.md
      - ML: entregas/segunda/ML.md
      - DD: entregas/segunda/DD.md
  - Entregas 3:
      - DER: entregas/terceira/DER.md
      - MER: entregas/terceira/MER.md
      - ML: entregas/terceira/ML.md
      - DD: entregas/terceira/DD.md
  - Entregas Final:
      - DER: entregas/final/DER.md
      - MER: entregas/final/MER.md
      - ML: entregas/final/ML.md
      - DD: entregas/final/DD.md
  - Referências: referencias/referencias.md 
  - Backlog: backlog/backlog.md

# Extra CSS
extra_css:
  - extra.css  # Arquivo CSS customizado