site_name: Call of Cthulhu
site_description: Documentação Oficial do Projeto Call of Cthulhu da Disciplina Bancos de Dados da Universidade de Brasília
site_url: https://mdsreq-fga-unb.github.io/2025.1-T02-CallOfCthulhu
site_author: Grupo 01 - Engenharia de Requisitos - UnB
repo_name: CallofCthulhu
repo_url: https://github.com/mdsreq-fga-unb/2025.1-T02-CallOfCthulhu
edit_uri: edit/docs/docs/

theme:
  name: material
  language: pt-BR
  custom_dir: overrides
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking
# Paleta
  palette:
    # Modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "teal"
      accent: "brown"
      toggle:
        icon: material/weather-night
        name: Mudar para o tema escuro
    # Modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "teal"
      accent: "brown"
      toggle:
        icon: material/weather-sunny
        name: Mudar para o tema claro
  
# For image rendering
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

plugins:
  - glightbox:
       touchNavigation: true
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       caption_position: bottom

nav:
  - Início: index.md
  - Entregas:
      - Primeira: entregas/entrega1.md
      - Segunda: entregas/entrega2.md
      - Terceira: entregas/entrega3.md
      - Final: entregas/entrega-final.md
  - Referências: referencias/referencias.md 
  - Backlog: backlog/backlog.md
