site_name: Call of Cthulhu
site_description: Documentação Oficial do Projeto Call of Cthulhu da Disciplina Bancos de Dados da Universidade de Brasília
site_url: https://github.com/SBD1/2025.1-CallOfCthulhu
site_author: Grupo 01 - Sistema de Bancos de Dados 1 - UnB
repo_name: CallofCthulhu
repo_url: https://github.com/SBD1/2025.1-CallOfCthulhu
edit_uri: edit/docs/docs/

theme:
  name: material
  language: pt-BR
  custom_dir: overrides
  logo: assets/logo.png  # Adiciona o logo
  favicon: assets/favicon.ico  # Adiciona o favicon
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking
# Paleta
  palette:
    # Modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "teal"
      accent: "brown"
      toggle:
        icon: material/weather-night
        name: Mudar para o tema escuro
    # Modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "teal"
      accent: "brown"
      toggle:
        icon: material/weather-sunny
        name: Mudar para o tema claro
  
# For image rendering
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

plugins:
  - glightbox:
       touchNavigation: true
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       caption_position: bottom

nav:
  - Início: index.md
  - Apresentação: entregas/apresentacao/apresentacao.md
  - Módulo 1:
      - Diagrama Entidade Relacionamento: entregas/primeira/DER.md
      - Modelo Entidade Relacionamento: entregas/primeira/MER.md
      - Modelo Lógico: entregas/primeira/ML.md
      - Dicionário de Dados: entregas/primeira/DD.md
  - Módulo 2:
      - Modelo Entidade Relacionamento: entregas/segunda/MER.md
      - Modelo Lógico: entregas/segunda/ML.md
      - Dicionário de Dados: entregas/segunda/DD.md
      - Data Definition Language: entregas/segunda/DDL.md
      - Data Modeling Language: entregas/segunda/DML.md
      - Data Query Language: entregas/segunda/DQL.md
  - Módulo Final:
      - Diagrama Entidade Relacionamento: entregas/terceira/DER.md
      - Modelo Entidade Relacionamento: entregas/terceira/MER.md
      - Modelo Lógico: entregas/terceira/ML.md
      - Dicionário de Dados: entregas/terceira/DD.md
      - Data Definition Language: entregas/terceira/DDL.md
      - Data Modeling Language: entregas/terceira/DML.md
      - Data Query Language: entregas/terceira/DQL.md
      - Triggers e Stored Procedures: entregas/terceira/TSP.md
  - Referências: referencias/referencias.md 


# Extra CSS
extra_css:
  - extra.css  # Arquivo CSS customizado