site_name: Call of Cthulhu
site_description: Documentação de desenvolvimento do Projeto Call of Cthulhu da Disciplina Bancos de Dados da Universidade de Brasília
repo_name: "2025.1-Call_of_Cthulhu"
repo_url: https://github.com/SBD1/2025.1-CallOfCthulhu

nav:
  - Início: index.md
  - Entregas:
      - Primeira: entregas/entrega1.md
      - Segunda: entregas/entrega2.md
      - Terceira: entregas/entrega3.md
      - Final: entregas/entrega-final.md
  - Referências: referencias/referencias.md 
  - Backlog: backlog/backlog.md
# Tema
theme:
  name: material
  language: pt-BR
  custom_dir: overrides
  logo: assets/logo.png  # Adiciona o logo
  favicon: assets/favicon.ico  # Adiciona o favicon
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking
    
# Paleta
  palette:
    - scheme: default
      primary: teal
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: teal
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  
# For image rendering
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - glightbox:
       touchNavigation: true
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       caption_position: bottom

# Extra CSS
extra_css:
  - extra.css  # Arquivo CSS customizado